name: 'Amazon ECS "Render Task Definition" Action for GitHub Actions'
description: 'Creates a new Amazon ECS task definition JSON file with new container image URI, environment and secrets from AWS SSM params.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The path to the ECS task definition JSON file'
    required: true
  container-name:
    description: 'The name of the container defined in the containerDefinitions section of the ECS task definition'
    required: true
  image:
    description: 'The URI of the container image to insert into the ECS task definition'
    required: true
  ssm-param-path-pattern:
    description: 'Path pattern used to load AWS SSM params and set to container definition as environment and/or secrets.'
    required: false
outputs:
  task-definition:
    description: 'The path to the rendered task definition file'
runs:
  using: 'node16'
  main: 'dist/index.js'
